### ISSUE TITLE
Variable round speeds

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#124]
Notify slayerofable@gmail.com when "lightning rounds/strategic play" game modes are available

**Comment by toddmedema** [comment]
Following up here (based on feedback from backer) that it'd make sense to split out round speed from difficulty, ie keep difficulty but have it not affect timer duration, then make "Round speed" with options "strategic (60s), slow (30s), classic (10s), lightning (6s)"

**Comment by smartin015** [comment]
Backlogging this for now.
