### ISSUE TITLE
(low) Offline support for online quests

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#134]
*Migrated to expeditionrpg/expedition#184 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

- allow users to download quests to be played in the future / when offline
- allow users to delete downloaded quests
- allow users to search through just downloaded quests while offline

UI:
- in the quest search list, quests should have a download button (that changes to "downloading" icon while downloading, and a delete button when downloaded)
- if you search for quests while offline, it should run the search against all downloaded quests

**Comment by toddmedema** [comment]
Note, this ties in with alerting the user when offline: https://github.com/Fabricate-IO/expedition-app/issues/126

**Comment by smartin015** [comment]
Backlogging for now (we have other stuff to focus on).
