### ISSUE TITLE
Cleaning up and testing choices

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#151]
As mentioned here, the calculation of choice and instruction counts could be passed off to the roleplay card for streamlining: https://github.com/Fabricate-IO/expedition-app/pull/148#pullrequestreview-11913332

While we're touching this code up, should also add in more tests:
- making sure instructions display
- conditional instructions work
- conditional choices work (esp when the first choice isn't displayed / isn't valid, to test for offset bugs)

**Comment by smartin015** [comment]
This is obsoleted by work in #288. Unit testing is covered in #27
