### ISSUE TITLE
Expose XML parsing errors to user

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#154]
*Migrated to expeditionrpg/expedition#185 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Ie if someone manages to publish an invalid quest, the app shouldn't crash / freeze

**Comment by smartin015** [comment]
From #331 - It'd be nice to also have a unit test - e.g. fake web response with bogus XML, to ensure we surface some error.

**Comment by toddmedema** [comment]
Based on the large things in queue for this month, backlogging this
