### ISSUE TITLE
Text input

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#160]
*Migrated to expeditionrpg/expedition#186 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Now that we have ops, we can also operate on more sophisticated user input than single button clicks.

- text input (secret passphrases, or fine value manipulation)
- multi-selection (perhaps for a better flow for purchasing items)
- sliders
- canvas-based input

Text input especially would allow more personalized stories, and thus more character building.

**Comment by toddmedema** [comment]
Seems like text input or `select` is a good starting point

**Comment by smartin015** [comment]
Backlogging for now
