### ISSUE TITLE
Add "Roll for party" batch random number generator to resolve screen

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#17]
Should be consistent even if you go back (for reference): generate on timer end.

**Comment by wls** [comment]
I had toyed with the idea of making it so when you touch the d20 icon, it rolls one.  But if it's going to be part of the resolve screen, even better.

**Comment by toddmedema** [comment]
Continue to hear people suggest this

Also, heard a cool suggestion - on top of a button to roll, you could also "shake to roll"
