### ISSUE TITLE
Firebase Analytics upgrades

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#180]
Building off https://github.com/Fabricate-IO/expedition-app/issues/79

- bug: why are there so many combat defeat and victory with players = null?
- quest starts: need access to settings.numPlayers
- quest ends: players, total play time
  - the card that they won / lost on? Would be really interesting as a writer to see the paths most people take
- track total time played for quest and combat (via quest.start timestamp?)
- for all events (quest starts and ends, combat, etc), include quest ID (not just name, name might change)
- combat: include max tier sum
- test with app crashes (if we haven't received any)
- implement + test notifications
- figure out a solution for the web version - hopefully they'll update plugin to [have web support](https://github.com/arnesson/cordova-plugin-firebase/issues/102) - if they're slow, make a fork + put in a PR; if they say no, look into the [web js version](https://firebase.google.com/docs/web/setup)
  - send JS errors (don't send errors related to sending errors)
  - once web version working, don't send analytics events if it's running inside of the quest creator (perhaps quest editor manually override the analytics send function, since it's on the window object?)

**Comment by smartin015** [comment]
We're migrating off firebase.
