### ISSUE TITLE
App font size too large inside of quest editor

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#194]
Believe the bug is due to the app improperly applying max-size CSS when the width of the container is smaller than max size

.... which would be because it's going off screen size, not container size....

@smartin015 we could use something like this, since CSS media queries only let you use page size, not div size: http://marcj.github.io/css-element-queries/ - possible downsides: performance (shouldn't be too bad, unless people are rapidly resizing windows lol), compatibility / bugs

OR, give the app custom CSS for when it's in the editor. But that seems like it'll be harder to maintain.

**Comment by danielwiktorczyk** [comment]
I've been having this issue too lately

**Comment by toddmedema** [comment]
CSS element queries could work, but we'll need to adjust it so that all queries are a nested part of `.base_card` - then, the styling mixin takes an input of min and max screen dimensions, and applies the element query format `.class[min-width~="400px"]` to `.base_card`

Tried this, and didn't have any luck on the first attempt :(

**Comment by toddmedema** [comment]
Idea here... we also have an issue for scaling the font size (for accessibility purposes) - https://github.com/ExpeditionRPG/expedition-app/issues/137

Since that'd be stored in the settings, we could make sure to have a "small" font size option that's smaller than the current font size, and have the quest creator use font size = small in the settings it passes to the app

**Comment by toddmedema** [comment]
Update: Slightly reduced the maximum sizing for app styles, should make it more manageable on desktop and tablets: https://github.com/ExpeditionRPG/expedition-app/commit/6bdeaba7896f20276295115b3ff5f9428e2683e0#diff-e11cce618e96b79be743111bd5c16a05R781

Closing for now, but if it feels like it's still too big, let me know!
