### ISSUE TITLE
Web app offline caching (via Service Workers / Redux Offline)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#250]
*Migrated to expeditionrpg/expedition#194 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

https://developers.google.com/web/tools/lighthouse/

Register a service worker: https://developers.google.com/web/fundamentals/getting-started/primers/service-workers

Responds with a 200 when offline

See the 9th point here: https://hackernoon.com/10-things-i-learned-making-the-fastest-site-in-the-world-18a0e1cdf4a7#.k8wkk41hk

**Comment by toddmedema** [comment]
Check out Redux Offline: https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0

**Comment by smartin015** [comment]
That's pretty damn cool. I say we give it a shot :)

**Comment by toddmedema** [comment]
Note that using this system of saving state offline also makes settings (and quest state!) persistent: https://github.com/ExpeditionRPG/expedition-app/issues/30

We would, however, need to be mindful of how this would work with multi-part quests. Perhaps, if your saved state had a quest / node defined, we could show a "resume quest XXX" button at the top.

Note that we might also need to be a bit thoughtful about / version states, so that someone who opens the app a month and three versions down the line doesn't crash... (but they also don't lose their state every time we update....)

**Comment by smartin015** [comment]
Sounds like we should make a list of offline-able state attributes, and make sure we don't change those :)

Quest state could be reloaded to a close approximation simply by the XML element they're on and the current context (aka a ParserNode instance). We'd also want to save their user settings as well.

**Comment by smartin015** [comment]
Backlogging for now. It's more useful to build more online functionality currently.
