### ISSUE TITLE
Complete existing unit tests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#27]
There's about 60-ish unimplemented tests that need to be filled out.

**Comment by toddmedema** [comment]
Unit test idea: Generate callout using specified icon and another by beginning icon, and test the output HTML for both for equality. From https://github.com/Fabricate-IO/expedition-app/pull/165#pullrequestreview-14815021

**Comment by toddmedema** [comment]
Test combat math / generateCombat attack. Account for randomness ideas:

- mock out Math.random to always return 1
- use a seedable RNG (https://github.com/davidbau/seedrandom), or
- split the function in two and pass in an array of "random" values into the inner function

**Comment by toddmedema** [comment]
A good thing to unit test: feel like checking for `== false` in ops should also return true if the variable is undefined? (would require extra code on our end) Or, is there some other (easy) way to check for "not true"? (`!= true` doesn't work if it's not defined)

**Comment by smartin015** [comment]
New policy: if we're working on a file that has incomplete tests, implement at least one in the PR. Closing this out for now.
