### ISSUE TITLE
Family Friendly setting

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#279]
Set in the settings, which then:
- auto-includes that param in search queries
- enables a profanity filter on quest content

(make sure to describe what it does as part of the setting checkbox)

**Comment by smartin015** [comment]
Profanity filter sounds cool and useful. I don't know if tying play speed to the FF setting works for everyone, though. Might be best to leave those types of settings to play difficulty instead.

**Comment by toddmedema** [comment]
That makes sense; keep it as a setting, but limit to search + profanity filter for now

**Comment by toddmedema** [comment]
Getting wrapped into search / content rating improvements: https://github.com/ExpeditionRPG/expedition-app/issues/327
