### ISSUE TITLE
Make settings persistent across sessions

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#30]
Use local storage? Might be a convenient Cordova plugin...

**Comment by toddmedema** [comment]
Notes from IRL:
- this could also be used to solve memory leak issues where state history grows too large (which seems to happen quite readily on older devices)
- we'd likely want to serialize the state into a string, then save into local storage (which would also allow you to resume state if the app crashed!)
- and then, on quest end, clear out the quest history to prevent filling up local storage too.
- but, we'll want to make sure we aren't serializing functions, and are properly restoring them. There's definitely some in quest context's `_`, there might be functions hidden elsewhere too

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-app/pull/465
