### ISSUE TITLE
Combat: Support for heal / loot / xp on lose

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#312]
Might as well add support for them on lose - and on all triggers in general - since they're programmatic outcomes that may be relevant in different situations. #GenericImplementation

For example, I'm writing a quest where you can continue on even if you lose because the rats are scared away (similar to Oust Albanus), where you'd (obviously) need to heal since everyone's dead.

**Comment by smartin015** [comment]
Backlog/moderate impact

**Comment by smartin015** [comment]
Dupe of #533
