### ISSUE TITLE
"Tavern" template

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#317]
Seems like a lot of quests involve spending a night at a tavern. We could abstract out a lot of the busywork - healing, purchasing a room, purchasing drinks/food, even randomly-picked rumors and conversation.

**Comment by smartin015** [comment]
Nice to have, but high effort. Backlogging for now.

**Comment by toddmedema** [comment]
Closing this as it seems to be a less generic version of conversation template: https://github.com/ExpeditionRPG/expedition-app/issues/406
