### ISSUE TITLE
Split out art / art assets to separate repo?

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#323]
Now that we have three repos (card creator, app, quest creator) all using the art in slightly different ways, it might make sense to split out the art assets, backgrounds and icons to a separate repo. This would make several things more convenient:

- keep all of the assets in a single place (better for maintenance)
- using icons and art in the card creator without having to import the entire app
- making it easier to reference / use icons in the UI (ie just import the icon from expedition-art/icons/undead rather than having to do a janky expedition-app/app/images/icons/undead)

Thoughts?

**Comment by smartin015** [comment]
Makes sense, although `expedition-assets` would be a bit more future-proof. Then we could include CSS and other stuff without stretching the name.

**Comment by toddmedema** [comment]
True! Like the material ui theme file, which is actually js

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-app/pull/504
