### ISSUE TITLE
Explicitly list exports to QC

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#350]
*Migrated to expeditionrpg/expedition#208 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

https://www.twilio.com/blog/2017/06/writing-a-node-module-in-typescript.html

There's a [bunch of places](https://github.com/ExpeditionRPG/expedition-quest-creator/search?utf8=%E2%9C%93&q=%22+from+%27expedition-app%2F%22&type=) where we reach deep into this repo for the editor to use the app. 

This is fragile - if the directory structure or filename changes, we'll break the quest creator when we try to sync. And since there's no strong interface boundary, there's not very good tracking of what's actually used by the IDE.

**Comment by smartin015** [comment]
In particular, cheerio and elements are sprinkled throughout the QC with type `any`, but there's a `CheerioElement` type def in the app that could be used for elements.

**Comment by toddmedema** [comment]
Thought: would it make more sense to instead use this as an opportunity to move shared resources to a separate repo entirely? If we use it in both the QC and app, it's pretty likely we'll also use it in future Expedition repos (chatbots, services, etc). We're already talking about a separate art repo, so perhaps it becomes a `expedition-shared` art / code / assets repo?

**Comment by smartin015** [comment]
Let's hold off on fully splitting until we have >=3 dependent repos.

**Comment by smartin015** [comment]
Backlogging/low impact
