### ISSUE TITLE
Native SVG handling

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#353]
*Migrated to expeditionrpg/expedition#209 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We could prevent the icon flicker-on-load issue (where `svg.js` loads and converts the image on the fly) by having a webpack thing that 'renders' all `*.svg` files to `*.tsx` files containing the SVG in jsx format.

**Comment by toddmedema** [comment]
or by loading the SVG file at insertion time, and inserting it as an SVG element rather than an img - https://stackoverflow.com/questions/23402542/embedding-svg-into-reactjs

**Comment by smartin015** [comment]
Backlogging/low priority
