### ISSUE TITLE
Pay what you want: Stripe Integration

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#362]
Stripe App Payment UI: https://stripe.com/docs/elements
Note: extremely similar to Braintree implementation at UI level
- [x] initialize Stripe script
- [x] insert `card-element` form element, initialize stripe against that element
- [x] listen to change events and show / hide errors
- [x] submit form data to our server's /charge endpoint and get back error (display & input phase) or success (thank you phase)
- [x] Style form, label, error messages
- [ ] Set up config file for Stripe and auth settings; default to test Stripe API key + existing auth settings
- [ ] Full test w/ local server running new endpoint: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/298
  - [ ] Test with quest w/ author w/ stripe, author w/o stripe and w/o author

Future:
- [ ] Apple Pay https://stripe.com/docs/apple-pay/web
- [ ] Android Pay
- [ ] enable bitcoin https://stripe.com/docs/sources/bitcoin

Notes from previous integration attempt:
- fix paypal
- detect and display API errors in CheckoutContainer... perhaps the complicated onSubmit logic should also be moved to an action
- detect and handle braintree API initial load errors - possible implementation: if you visit checkout and braintree isn't defined, attempt to load it again - and if THAT fails, then show an error to the user
- integrate sandbox with Apple pay, test on iOS app -> integrate prod account
- integrate with Android Pay (probably need a Cordova plugin for that...)
- server: create customer, store as user.braintree_id, pass customer_id back to client + use to initialize braintreeInstance
  - https://developers.braintreepayments.com/guides/customers/node
  - add `user` table that tracks id, braintree_id, created, lastlogin
    - concern: id from Google Auth not a permanent user id?
    - could combine w/ mailchimp api, store mailchimp user id so that we don't keep trying to subscribe people + in the future can expose an unsubscribe option
  - upgrade to vault flow... I think this might happen automatically if you have customer_id and payment methods associated with that customer....
    - create default payment method: https://developers.braintreepayments.com/reference/request/payment-method/create/node
    - show something in the UI to indicate that payment methods are saved - ideally a checkbox that allows people to opt out of saving it
- add our own `transaction` table that tracks everything braintree does - user email, user id, product category, product id, amount, timestamp - as backup + so that we can do our own analytics + reporting

**Comment by smartin015** [comment]
Backlogging for now

**Comment by smartin015** [comment]
dooonnneee
