### ISSUE TITLE
Slowly ramp damage when at least one player dead

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#366]
Prevents combat from going on forever and ever. Also makes sense b/c enemies have fewer people to target. Note: NOT ramping damage when there's only one player, which would totally break single-player.

Perhaps something like 5% per round post-death? After 5 rounds, enemies deal 25% more damage, after 10 rounds they're dealing 50% more damage. Which seems pretty reasonable, since sitting out of combat for 10+ rounds as a player would be pretty lame. I could also see 4% (20% and 40% respectively) if we wanted to be a bit more cautious in our balance tweaks.

Success metric: reduce average combat duration without reducing win rate (basically, if it's clear you're going to lose, get it over with faster). Of course, we aren't currently tracking this data as Google Analytics doesn't let you send such nuanced information, so if we actually wanted to monitor this metric we'd have to do a separate issue before this one to add internal analytics, and then let that run for at least a week to have comparison data...

**Comment by smartin015** [comment]
May as well start with 5% and see how it goes :)
