### ISSUE TITLE
Nav - debouncing does not affect analytics / extra events fired

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#373]
Even though we disabled navigational debouncing, noticing that analytics events still get fired (ie quest starts when going from the splash page to the featured quests page)

Perhaps the navigate action should support + fire a callback, but only if the navigation is successful? The callback could be fired before the page is changed, so that things can be loaded before the UI changes

**Comment by smartin015** [comment]
Where are we doing the debouncing? Sounds like this could be done earlier in the flow/before GA is called.

**Comment by toddmedema** [comment]
Closing, unable to reproduce
