### ISSUE TITLE
Review all outstanding quests for quality

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#385]
Send feedback to all authors. If there are any that are especially bad quality, also let them know that the quest will be unpublished until they have a chance to fix the issues to insure the best possible experience for adventurers.

THEN, adjust the app to make community quests seem less intimidating, perhaps by calling it "More Quests" and then going to the filter page (with a search button). Also perhaps adjusting the disclaimer to be less intimidating, ie "We do our best to curate these quests, but if you encounter any that are inappropriately labeled, please report it by going to the menu icon in the top right and choosing "Report Quest" while playing it"

FINALLY, make sure to play through and review all quests as soon as they're published, to maintain a high level of quality.

Ad'tnl thought: email us on major publishes, not just new publishes?

This higher standard of quality will also make the PWYW marketplace more effective

**Comment by toddmedema** [comment]
Done! All quests have been reviewed, polished, and updated. Just in time for a bunch of new people getting copies and checking it out for the Kickstarter :)

**Comment by smartin015** [comment]
Awesome, thanks for doing this.
