### ISSUE TITLE
Expansion UX

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#386]
Once app PR live:
- QC: update app version, make sure {{_.contentSets()}} works (though keep hidden for now)
- QC: if quest set to require "The Horror", enable it in app settings via renderAndPlay

At the start, ask if they have expansion (if setting.contentSets || contentSets.horror undefined)
- DONE: Store as dictionary of enabled content, ie {horror: null / true / false} - use null state to tell if they've been asked yet or not
- DONE: Save to settings & localStorage
- DONE: Modal. Noting that this can be changed at any time in settings
- DONE: Ability to change in settings

If true:
- DONE: Web: showcommunity quests that are expansion-pack-only
- DONE: Add a new "Learning to Horror" quest that specifically teaches the new Horror / Persona mechanics
  - Update featured quests page to only show it if horror enabled
  - Each persona card has 5 levels; the intermediate levels (indicated by arrows) offer no bonuses. You cannot go over Max or under Min. Right before you resolve abilities, any players at Min / Max will resolve their effect and then return to Base persona.
  - Your persona reveals details about your character(s) and how they react to events and situations in the game. As your persona changes, your character(s) will react differently to the world around them. For players who enjoy roleplaying, this adds a lot of new depth to characters. Of course, roleplaying is not required.
  - Influence abilities and Horror surges will raise and lower your persona level. Your decisions in quests can also affect your persona - if they do, the quest will tell you.
  - Persona levels persist across fights.
- DONE: review / update expansion rules (https://docs.google.com/document/d/1n-zMfg9mHNFAY6LSgt-IygzipwfBNd2y576Qqumtfr8/edit) and apply them to the app
  - Quest Setup: draw a persona and set to Base. Everyone draw 1 influence ability (start with 7 abilities).
  - resolve phase: resolve any personas at min / max, then return them to base (before resolving abilities)
  - adventurer phase: if alive players < numPlayers, show current hp = 0 rules, plus resetting persona
  - end of combat leveling up: all adventurers can also learn influence abilities.

Consider:
- DONE: You may choose when to spend max persona? Ie doesn't have to be the very next round. more strategy around use + a bit of a gambling / push your luck mechanic

Behind the scenes:
- DONE: add new encounters to config list
- DONE: make sure they only show up in .randomEnemy() if horror is enabled
- DONE: Quest Creator: new button and DB column for requires_the_horror

**Comment by toddmedema** [comment]
Also note at end of combat that persona damage is not healed (unless you get knocked out, and then you return to base)

**Comment by smartin015** [comment]
Adding in the expansion rules (if quest is horror expansion) is tagged for EoSeptember
