### ISSUE TITLE
(Greg) "Guided adventure" quest

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#401]
*Migrated to expeditionrpg/expedition#212 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

And notify J D via email

**Comment by toddmedema** [comment]
Working on it here: https://quests.expeditiongame.com/#0B7K9abSH1xEOUXROZkw0OVg0Sk0

**Comment by smartin015** [comment]
Backlogging - other priorities at the moment.
