### ISSUE TITLE
Map navigation card template

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#410]
*Migrated to expeditionrpg/expedition#214 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Load an image with certain tappable touch points  for use in navigation (adds more realism than a couple of buttons with names of things). 

Low-impact, but high production value.

**Comment by toddmedema** [comment]
Back-logging this for now, lots of things we'd have to sort out before this (such as images in quests)
