### ISSUE TITLE
Add to F-Droid Repository

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#413]
https://f-droid.org/contribute/

**Comment by toddmedema** [comment]
"May not use proprietary analytics packages like Firebase" https://f-droid.org/wiki/page/Inclusion_Policy

Also, many not use any proprietary libraries anywhere, so I suspect there would be a lot of extra pain to make the adjustment. IMHO not worth our time right now, but we'd always welcome contributions from someone else to make it happen :)
