### ISSUE TITLE
Small style improvements

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#435]
Inspired by: https://codepen.io/tyrellrummage/full/ZJPXgy/

- Lighten icons when used as simple identifiers for buttons (e.g. "More Quests", "Tools")
- Add a subtle shadow to white-on-red announcement banner & surge page (e.g. `text-shadow: 0 1px 2px rgba(0,0,0,0.3)` looks nice)
- Add a slight box shadow on pop-up interactives (`box-shadow: 0 2px 3px 0 rgba(0,0,0,.275) !important` for button, for instance)
- Break up setup numbered bullets into "Adventurer", "Abilities", and "Sundries" to make less monotonous
- Cream-ify the settings flyout so it looks thematic
- Add slight extra padding between picker & descriptive text
- Add extra spacing between characters in capital-y Cinzel Bold  font (`letter-spacing: 1.3px`)
- Div class `article` shouldn't have padding; it cuts off background icons and makes less space for text.
- Intro quest should use background iconography
- Decrease button border intensity (`#666` for light theme)

**Comment by toddmedema** [comment]
Note: the pop-up interactive when you open the top right menu already has a drop shadow

**Comment by smartin015** [comment]
Reopening to handle shadow on buttons & pickers

**Comment by smartin015** [comment]
Additionally: should add `min-height: 50vh` to `.base_card .article .scrollbox` to prevent scrollbar from appearing when a short roleplay card has a background icon.
