### ISSUE TITLE
Add save button to settings page?

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#438]
It's the only page where the "back" button persists state. This is a bit weird.

We could keep the state persistence for a few months, but I think it'd be better to have a "save" button at the bottom of the settings page that people can click to specify their intent.

**Comment by toddmedema** [comment]
Maybe, but looking at other mobile apps (Inbox, Habitica, Chrome), all of them just use the back button for their settings page / saving is implied.

If we wanted to make it clearer that it was being saved / get complaints about this, we could always show a snackbar toast "settings updated" when you go back from settings. I haven't heard anyone be confused over this, but I also haven't watched a bunch of people using that part of the app, so it's possible that it's momentarily confusing.
