### ISSUE TITLE
Remote play demo

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#446]
Colors from https://github.com/ExpeditionRPG/expedition-app/issues/472
![30487711-40353e44-9a02-11e7-8396-9d1cd2e66cc2](https://user-images.githubusercontent.com/775657/30522274-62bc83f6-9b9b-11e7-9145-c8206cbe86bd.png)

**Comment by toddmedema** [comment]
Colors from https://github.com/ExpeditionRPG/expedition-app/issues/472
![30487711-40353e44-9a02-11e7-8396-9d1cd2e66cc2](https://user-images.githubusercontent.com/775657/30522274-62bc83f6-9b9b-11e7-9145-c8206cbe86bd.png)

**Comment by smartin015** [comment]
Suggestion from #475:

<em>Idea from last night: each action includes a hash of the current state (not the entire state, since that would include local settings - perhaps just the hash of all history.action_names? or the hash of the currently displayed HTML? or even just history.length?). The receiving client hashes its own state before running the new action to confirm that it's in sync

If the receiving client recognizes it's out of sync, it requests a force sync, which would either be downloading all of the current state, downloading all past actions, or some other mechanism by which a client that gets disconnected / is in an untrusted / corrupted state can resume playing.</em>

**Comment by smartin015** [comment]
Action items:
- [X] Rewritten dispatch flow for async hooks
- [X] Synced basic navigation
- [ ] Improved test toolkit (automatically sets up remoteify reducer stuff)
- [ ] Rewritten non-remote actions (dialogue, announcement, settings, snackbar, user, feedback)
- [ ] Console warnings when actions not using `remoteify`
- [ ] Synced quest loading
- [ ] Synced roleplay actions
- [ ] Synced combat actions
- [ ] Finalized lobby UI
- [ ] Finalized remote UI overlay footer
- [ ] Finalized basic network code & authentication
- [ ] Alpha version published, feedback gathered
- [ ] Iteration on alpha feedback
- [ ] Network security review & load test
- [ ] Larger closed beta version published, feedback gathered
- [ ] Iteration on beta feedback
- [ ] Open beta

**Comment by smartin015** [comment]
Design decisions:

- We'll allow async actions, but rewind the user when another transaction supersedes theirs.
- This requires a sharded counter per session that allows for ordering events.
- Napkin math indicates that at a 3x sharded counter and 100 remote play quests per day, we'd be hard pressed to go over even $4 a month in Firestore quota.
- We'll hold off on event garbage collection for now for similar reasons (gives us a source for analysis).

UX for timer card:

- Show "Waiting for N players", and replace the timer with the player count when local timer is held.
- Pulse the logo black<->red, 0.75 seconds per pulse (to indicate urgency but not a direct time value)

UX for "rewind"

- Fade to black while showing spinner and "synchronizing..." text
- Fade in the previous choice/action by the other user, show touch-ripple, then slide to the new value.

**Comment by toddmedema** [comment]
Note, there appears to be a bug when attempting to leave RP sessions

**Comment by smartin015** [comment]
IT'S FINALLY DONNEEEEE
