### ISSUE TITLE
Make 0 search results UI more fun

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#450]
*Migrated to expeditionrpg/expedition#219 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Earns goodwill; also a chance to provide a bit of instruction, or a handy shortcut for broadening results

**Comment by toddmedema** [comment]
Backlogging since it didn't make it into this bug sprint

**Comment by ezittel** [comment]
#709 added

**Comment by ezittel** [comment]
![image](https://user-images.githubusercontent.com/16277302/40544333-e3406744-5ff5-11e8-80a8-7a7c2feb25cb.png)
