### ISSUE TITLE
Verify/fix shown/hidden round counter info

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#451]
Doesn't seem to be behaving correctly.

**Comment by toddmedema** [comment]
Might be related to https://github.com/ExpeditionRPG/expedition-app/issues/439, ops not working correctly in * on round

**Comment by toddmedema** [comment]
Nope, it's actually https://github.com/ExpeditionRPG/expedition-qdl/issues/13

Since that's a QDL issue and not an app issue, closing this one
