### ISSUE TITLE
Fade out "TO BEGIN" instructions on splash during interaction

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#455]
Currently the splash page instructions disappear and reappear slowly when releasing a tap before the timer expires. We could just fade the instructions away when the touch begins to make this feel more natural.

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-app/commit/976deb26c827d9e115139aeac5873c78aede6d8b

Will be on beta in a few minutes. I do like the fading.... if you're looking at it, also gives you a sense for how long you have / that you have a "second" / it's not an instant thing.
