### ISSUE TITLE
Settings flyout menu has white artifacts when animating

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#457]
Looks almost like the background is being applied to the wrong element - there's an element that expands with whitespace before the background fills it.

**Comment by toddmedema** [comment]
Tried every option to us in the MaterialUI API for IconMenus, nothing fixed it :( And then discovered that it looks like IconMenu won't even exist any more in Material-UI 1.0. So, since we'll probably change this implementation in a few months, I'm fine closing it for now.
