### ISSUE TITLE
Ensure private publish also seaches for expansion quests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#459]
I suspect that horror quests won't be shown unless `expansions: ["horror"]` is set.

**Comment by toddmedema** [comment]
Solved by a combination of actually sending expansionhorror on publish: https://github.com/ExpeditionRPG/expedition-quest-creator/commit/896bbae25bf365fb97427a72b897f5d573ebebb0

And including expansions: ['horror'] in private quest search: https://github.com/ExpeditionRPG/expedition-app/commit/85f4af0ff1c5efb398f8ae58b05f642826320206
