### ISSUE TITLE
Better combat flow for abilities that reflect damage... and better help?

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#461]
@smartin015 I feel like we can collapse the damage and adventurer count cards into one:

1. There's a good amount of confusion (and annoyance) around abilities that reflect damage and force you to go backwards in the app if you kill an enemy with them.
2. Adventurers don't die that often, so forcing people to click through a page every....single....round.... just for that purpose is pretty low-hanging fruit as far as making the experience even more streamlined goes.

I guess the main question is.... can we fit both on a single page?

We should be able to fit All Adventurers' Damage on one line... but there's a lot of help text for each of the number trackers, as well as talking about what happens if you reach zero health.

Here's a thought.... what if they were expandable? Ie each of these sections had a single sentence with a (?) next to it, and tapping on it would cause a dialog to appear (or the extended help to slide down) with more information. For example, something like: Adventurers at or below 0 health (?)

We might even be able to get rid of the "Show help?" setting entirely if we did a good job of minimizing the UI space these prompts take up, while also having them there for easy access to these common rules questions.

Another implementation would be to have Menu -> Help on each page, which would show page-specific help (for example, on the roll & resolve page, clarifying common R&R questions). I'm less of a fan of that because it's hidden from users, and the very people we're trying to help (those new to the game) are the least likely to be aware of it + most likely to get frustrated.

ALSO: Roll & Resolve is the last bastion of the "giant wall of text", so streamlining / clarifying / improving that would polish the experience :)

**Comment by smartin015** [comment]
Let's try and merge them together, hiding the "adventurer at 0 health" instruction until there's actually an adventurer with 0 health present.
