### ISSUE TITLE
Saving spot in quest

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#466]
As talked about here: https://github.com/ExpeditionRPG/expedition-app/pull/465 - now that we have access to local storage, we can save and load quest state strings.

Thoughts / questions:

- Initially limiting to one quest save at a time should be fine for the majority case. Especially given the limitations around storage size, and the fact that iOS can wipe storage at any time, makes me think that storing multiple quest states might require some pretty significant hijinks.
- Could save as two key, values: quest id and the state string? Maybe also name too, so that even if you're offline, the app can still show "resume playing QUEST NAME"
- Question: Is state serialization working? What does that look like?
- Question: how big are serialized state strings? (localstorage is limited to 5MB). Specifically, how does the length of the string grow with the size of the quest, and with how far players have played into the quest. Note that for the sake of storage, I think it would be reasonable to only save the current state / not the entire history.
- Question: How would the load / resume function work? Presumably the app would need to have access to the quest XML. Perhaps we are also able to fit the XML in the localstorage 5MB, as a first implementation of offline quests? (ie if you start playing it, you can keep playing it even w/o a connection)
  - Mistress Malaise XML is only 17kb. Doubled for string encoding, we could still fit a single quest that's 140x longer than MM (aprox 32,000 lines of XML) into 5MB local storage.

**Comment by toddmedema** [comment]
Another possible implementation would be to use this cordova SQLlite plugin, which (as far as we can tell) does not have any storage limits: https://github.com/litehelpers/Cordova-sqlite-storage

Of course, there end up being numerous architectural challenges, including how to handle migrations of saves from old engine versions when we deploy updates (to which Scott suggests running the same play-path through the crawler to re-generate the current save position) and handling updated versions of the quest (to which I suggest saving the version of the quest you're using locally, and only playing off that / not allowing it to be updated mid-save)

Many of these things will end up being solved (or at least refined) as part of remote play, which is also more urgent given its promise to backers, so I'm backlogging this for now.

**Comment by smartin015** [comment]
Reopening this as the referenced PR has a functional prototype of quest saving.
