### ISSUE TITLE
Not working with certain phones

### ISSUE THREAD

**Issue by Drakensin** [ExpeditionRPG/expedition-app#470]
I have the Motorola E and when I open the app, it opens and stays on a grey screen.

**Comment by toddmedema** [comment]
That's no good! What version of Android is your Motorla E running?

We've gotten one other bug report, of a Galaxy Tab A running Android 5.0.2 having similar issues. Seemed like a one-off issue at the time, but might be a bug with Android 5.0.2?

**Comment by Drakensin** [comment]
I have the Motorola E 2nd Gen running on Android 5.1

**Comment by toddmedema** [comment]
@Drakensin I found a 5.1 device in our house and couldn't seem to reproduce. Could you try uninstalling the app, restarting your phone, and re-installing the app?

Failing that, you should be able to use the web app without issue (https://app.expeditiongame.com/), but it would be nice to figure out what's going on here.

**Comment by Drakensin** [comment]
@toddmedema It still has an issue running so I did the app online and it works
