### ISSUE TITLE
Conditional text via {{var == true}} text (at start of paragraph)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#473]
Seems like a very useful feature (good arguments made here: https://www.reddit.com/r/expeditionrpg/comments/70caz4/feature_request/)

And borrows a well-constructed idiom from Handlebars: http://handlebarsjs.com/builtin_helpers.html

Open to other implementation methods, but definitely think there's value in allowing writers conditional control over body text, not just choices and instructions :)

**Comment by smartin015** [comment]
It exists in handlebars, but we don't currently have any idioms from handlebars in the rest of our code. I think it'd be more QDL-like to prefix a paragraph with a "visibility" op, something like:

```markdown
{{{var == true}} This text is shown
Could potentially even be a long paragraph of text.

{{var == false}} This text is hidden because the op evaluates to false
```

i.e. people do the same thing as on every other card/node, just with paragraphs too.

**Comment by Wootai** [comment]
I wrote the original comment on reddit. 

I think that the prefix method is much more QDL-like. In my initial evaluation I had suggested the @ symbol as a marker for elements that are conditional text (similarly to how instructions and choices are marked with the > and *) and when evaluated would display as normal card text. 

The drawback to this would be that it limits the ability to have conditional text as only separate paragraphs and not allow it to appear within a paragraph but is a good compromise for such a ddynamic and useful tool.

**Comment by toddmedema** [comment]
I think `{{var == false}} This text is hidden because the op evaluates to false` would be the most intuitive way of doing it, since that's how we handle it with everything else. Especially if we require it to be a conditional check `{{var == false}}`, and if it was just `{{var}}`, we'd show the variable like normal / is currently the expectation.

**Comment by toddmedema** [comment]
Update here! This'll be added in the next update to the Quest Creator and app later today :)
