### ISSUE TITLE
Greybox end to end testing

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#479]
*Migrated to expeditionrpg/expedition#220 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

https://hackernoon.com/detox-gray-box-end-to-end-testing-framework-for-mobile-apps-196ccd9564ce

**Comment by smartin015** [comment]
Neat :) This could definitely be useful for catching the big stuff (app fails to load, basic user actions not functional, etc).

**Comment by smartin015** [comment]
Backlogging... this is a lot of extra test infrastructure to maintain (when we have QA already).
