### ISSUE TITLE
In combat roleplay: white icons

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#484]
At this point, would certainly make sense to switch back to rendering icons as pure SVGs instead of <img> tags, so that we don't have to manually create and maintain white versions of every icon.

(Note: the card creator does this... but uses the SVG injector.... there must be a way to render it into an SVG before inserting it!)

Potential implementation if we can't otherwise get SVGs to render before insertion: use font icons / turn icons into font set: https://icomoon.io/app/#/select

**Comment by ArcanaIreanol** [comment]
FYI, for now, we can use the workaround `_white`
```
* {{ malus }} on round
 
  > :roll_white: You are drunk, -1 to all your rolls during this combat
```
--> shows in white

**Comment by toddmedema** [comment]
True! Though not all icons have white versions, and it's a pain to create two separate versions of each, so definitely want to figure out a way to do this programmatically at some point :)

**Comment by ArcanaIreanol** [comment]
Plus: it takes some memory each and every time.

I think the app is web based (CSS I saw). Maybe a class-capable SVG would do the trick (same goes for the "bold" version for small icons, you could choose to hide or not the extra shape)

**Comment by toddmedema** [comment]
Yep, app is web-based! Should be pretty straightforward, really - use something like this to turn the existing IMG elements into SVG elements so that they can be styled - https://snippetlib.com/jquery/replace_all_svg_images_with_inline_svg

Oh wait, turns out there's an even easier version - https://github.com/atomic-app/react-svg

On moment...

**Comment by toddmedema** [comment]
Whelp... I'm back. After diving way too deep, looks like we'd have to re-architect most of the app UI to make this work automatically :( So, looks like we'll have to stick with `_white` for the foreseeable future!

**Comment by ArcanaIreanol** [comment]
``` 
* on lose
    too bad
    ** end **
```
