### ISSUE TITLE
_.generateEncounter(tier, class); _.estimatedPartyTier()

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#485]
*Migrated to expeditionrpg/expedition#221 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Useful in situation where the combat difficulty changes siginificantly based on player decisions.

**Comment by smartin015** [comment]
Another potentially useful scope function would be "estimate the tier of combat that's appropriate given combats and loot rewards so far"

**Comment by toddmedema** [comment]
Ooh yes, that's pretty much the exact use case the author who suggested this was trying to emulate.

Seems highly related to the crawler features we'd discussed a while back that would show writers the estimated minimum and maximum odds of success for each combat.

**Comment by ArcanaIreanol** [comment]
I'm leaving a comment here because we faced it by testing the app: when we are too many players, it's going to be too easy. randomly adding foes to combats when there are more than x players would be nice

**Comment by toddmedema** [comment]
Backlogging
