### ISSUE TITLE
Squarespace github & developer mode

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#486]
https://developers.squarespace.com/using-git

https://developers.squarespace.com/beginner-tutorial/

https://support.squarespace.com/hc/en-us/articles/206545717#toc-what-do-i-need-before-getting-started-

@toddmedema Thoughts? Revisioned, fully-customizeable styling and themeing while still keeping the WYSIWYG content editing flow seems pretty good to me...

**Comment by toddmedema** [comment]
Seems legit :) looks like it's the theme but not the contents, but that's still an improvement!
