### ISSUE TITLE
"Horror" quest theme

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#501]
Quest Creators will be able to select the theme (default: "Classic"); if it's set to "Horror":

- Create a new background texture for roleplaying cards, perhaps something desaturated?
- Create a new header separator SVG, perhaps a hole in the center with tentacles reaching to the left and right?
- Select new header and body fonts that are still legible, but more evocative of the horror theme. Perhaps a handwritten font for the header, and a /slightly/ less uniform serif for the body?
- Also use the new styling when viewing the quest details page for the quest, perhaps including a faint tentacle SVG that seems to be coming from behind the quest title.

**Comment by smartin015** [comment]
Backlogging (ETA in May 2018)
