### ISSUE TITLE
custom "on lose", "**lose**" heal / loot amounts

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#533]
*Migrated to expeditionrpg/expedition#226 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Both for trigger-based lose page and defaults for "* on lose"

**Comment by smartin015** [comment]
Deduping https://github.com/ExpeditionRPG/expedition-app/issues/312

**Comment by toddmedema** [comment]
This would be nice, but not as important as other outstanding issues
