### ISSUE TITLE
Feature idea: _.adjustCombatTier(delta)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#538]
*Migrated to expeditionrpg/expedition#227 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Now that writers can tell players to add and remove enemies in the middle of a combat round, would be nice to allow them to automatically adjust the tier...

**Comment by smartin015** [comment]
Backlogging.
