### ISSUE TITLE
If user not logged in, state.user is null (and possibly other side effects?)

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#567]
Figuring out the root cause of this and resolving it will prevent a LOT of bugs.

Originally assumed it was introduced by our upgrading of minify, but this seems to be true on local dev as well...

There are currently two monkey patches in Web Actions to deal with this (settings user = user || {}); removing them is a good way to check if the issues is fixed.

This may also be the cause of an error when you try to submit a review while logged out. It attempts to submit a review, but doesn't have access to user.id (despite you having just logged in), causing the API to (validly) reject it due to lack of user.

**Comment by smartin015** [comment]
Taking a look at the fixes here: https://github.com/ExpeditionRPG/expedition-app/pull/569/files#diff-5dae9fcbb6cd163f1a47087c5f6570adL75

There were a bunch of instances where failure to silently login would callback with a null user object. That particular instance of nullability is fixed. Todd - can you still repro with the web actions fixes removed?

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-app/commit/fabc93c0023a0776ea7c41a5d3955a091cb280df
