### ISSUE TITLE
"Did You Know?" Splash screen section

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#57]
- Mention battery life
- Turn your phone off silent for haptic vibration feedback 
- "Adventurers that work as a team are 37% more likely to not die all the time."
- The backs of Encounter cards can be used for custom enemies
- Searching community quests defaults to showing quests for the number of adventurers you select
- Write your own quests at Quests.ExpeditionGame.com

**Comment by toddmedema** [comment]
More a nice to have vs other high impact bugfixes and features
