### ISSUE TITLE
Intercept, cache, and report console.log/console.error calls

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#581]
It'd be super useful to have a handy list of logged console events whenever a user reports an error (e.g. in remote play). AFAICT this would be a matter of wrapping console.log and appending to an array or string every time something is logged to the console. 

We may end up with overly large packet size when we upload though... unsure about what we'd need to do to pass e.g. 8k+ of text.

**Comment by toddmedema** [comment]
Or, we just pass the last 10 or 50 console logs, since anything before that is unlikely to be relevant to the specific bug (or be repeat logs from the same issue) :)
