### ISSUE TITLE
Fix remote play edge cases

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#615]
*Migrated to expeditionrpg/expedition#234 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

- [ ] exiting remote play does not actual exit 
- [ ] Disable remote play button when in remote play
- [ ] Fix button IDs when different fundamental app settings  (hashed key for button IDs).
- [ ] Compute shared settings for remote play (e.g. intersection of app expansion list) and display it on the lobby page.
- [ ] shouldn't be able to go to "select adventurers" page during remote play (after splash screen double tap)
- [ ] Clear history when starting remote play (prevents back button weirdness)
- [ ] handling side effects (such as vibrations) during replays
- [ ] should prevent joining a session if it would put the total adventurer count over 6.

**Comment by toddmedema** [comment]
Added that exiting remote play does not actually exit
