### ISSUE TITLE
Only allow multiplayer between apps running the latest version

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#679]
*Migrated to expeditionrpg/expedition#248 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

In the same way we do the version check when fetching announcements, it might prevent headaches if we explicitly don't allow people to start / join multiplayer unless their app is running the latest version / show them a dialog indicating that they need to update their app to the latest version to play.

Perhaps simplest to disable the multiplayer menu button and show "please update" text in the button if outdated, rather than adding yet another dialog or leading on users any more than necessary

**Comment by toddmedema** [comment]
@ezittel this would be another good PR to learn on. We're currently fetching the "newest" app version and comparing it to the app's current version here - https://github.com/ExpeditionRPG/expedition/blob/master/services/app/app/actions/Announcement.tsx#L28

But we aren't storing it to the state. If we dispatched an action to update the announcement state to include something like `appUpToDate: boolean` (and add that field to the announcement store), we could then use that to change the multiplayer tool button to disable it and show "please update" text.

Let me know if that makes sense or if you have any questions!

**Comment by ezittel** [comment]
I'm not going to get to this tonight, but I'll start in on it over the weekend.
