### ISSUE TITLE
Analyze feedback and add checkboxes for user ratings

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#688]
*Migrated to expeditionrpg/expedition#253 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Checkboxes users can use in reviews, e.g. "spelling/grammar", "story too slow", "confusing"...
Could use these to fire off tailored cron emails with specific feedback.

**Comment by toddmedema** [comment]
Oooh, good point about firing off tailored emails!
