### ISSUE TITLE
Show "official" and "award-winning" in quest listing and details

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#714]
In the list elements, show official (logo) and award icons in the top right.
In the details page, show `<logo> Official quest` and `<awardIcon> Winner of (quest.awarded)` if quest.official / quest.awarded (which default to false and empty string)

**Comment by ezittel** [comment]
Do we have an icon for award?  I don't see one anywhere - I'd like to get both indictors in on one change.

**Comment by toddmedema** [comment]
We don't have an expedition-ified icon for that, so I usually turn to the official material UI icon set. This one, "stars", looks like a good option - https://material.io/tools/icons/?icon=stars&style=baseline

Should be able to import it and use it with: `import StarsIcon from 'material-ui/svg-icons/action/stars'`

**Comment by toddmedema** [comment]
Slight change: been thinking about how to make the `awarded` part work best for a variety of situations (ie winning an award, contest, etc), and think we'll have the least headache if we just use the entire string from the database / don't have a hardcoded preface string - so the frontend would just be `<StarsIcon/> {quest.awarded}`

**Comment by toddmedema** [comment]
To test the awarded tag, I've updated a recent award-winning quest to have the appropriate info: `The Mysteries of Ironwood Hollow, Chapter 1: The Long Road` by Ducky_Fowler: 4-6 players (since it's 4-6 players, make sure to set your local dev to 4+ players to see it in search!)

**Comment by ezittel** [comment]
![image](https://user-images.githubusercontent.com/16277302/40693917-f3bdfc86-6387-11e8-9bd6-ca0dd41b8d74.png)

![image](https://user-images.githubusercontent.com/16277302/40694028-7a93dd16-6388-11e8-88da-7e60d6d87c80.png)

**Comment by ezittel** [comment]
Hmmmm...why aren't I seeing this quest at all?  I have the settings set 
to 6.  My list starts with The Dead Wastland Chapter Two and ends with 
Example Quest TItle May.  Any idea? I know that's rather cryptic to 
troubleshoot.

**Comment by toddmedema** [comment]
Ahhh, because the local dev instance defaults to running against the beta API. Just modified the dead of wasteland quest on the beta DB to have the awarded info :)

Hmm - looks like the logo icon needs some styling adjustments to get aligned with the other icons! Are you comfortable with CSS or learning CSS to fix that?

**Comment by ezittel** [comment]
After some changes in css here's what I've got:
![image](https://user-images.githubusercontent.com/16277302/40724526-3c4ab3ec-63ef-11e8-9151-837b70e4da29.png)

**Comment by ezittel** [comment]
And here's the details page with icon and {quest.awarded} text from the db:

![image](https://user-images.githubusercontent.com/16277302/40726277-653a5c54-63f3-11e8-85ff-a22c028e109b.png)

**Comment by ezittel** [comment]
Okay trying again... #717

**Comment by toddmedema** [comment]
Done! Thank you for all of your help :)
