### ISSUE TITLE
Add spinner to quest search 

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#718]
Should move to the next card the moment the search button has been pressed, and show a spinner until the results have been received. Otherwise it feels like the UI is slow - even to the point of feeling like the app has crashed on a slow connection.

Note that this can happen both from the filters page (if you were logged out or you change the filters) and from the main menu -> search (if you're already logged in)

**Comment by ezittel** [comment]
I will conduct some functional tests and code analysis.

**Comment by toddmedema** [comment]
Great ideas!

So, it turns out... we apparently added this functionality a while back, but it's broken - https://github.com/ExpeditionRPG/expedition/blob/master/services/app/app/components/views/Search.tsx#L339

So the real question is now, why is this not working? If I had to guess, it might be something about the active page not being changed to SEARCH until after the search returns, when we really want it to change ASAP and have the loading dots appear until the results are ready.

Up for taking a crack at this? If so, I highly recommend trying out the Redux DevTools extension, so that you can follow along with what actions are getting called - https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en

**Comment by ezittel** [comment]
` {results.length === 0 && props.searching && <div className="lds-ellipsis"><div></div><div></div><div></div><div></div></div>}`

(I wondered what that did, now I'm understanding what this is for)
We're waiting for the asynchronous call to complete.  
Until it does, show "..."
Then show results.

So this is saying:
if the results.length is null or 0...

but we want:
WHILE the results.length is still null or 0...

So is it possible to refactor this as a promise, and is that even the right concept to be using?
There is also the onUnmount() event in the component I saw being leveraged, something like this:
https://stackoverflow.com/questions/36985738/how-to-unmount-unrender-or-remove-a-component-from-itself-in-react

**Comment by ezittel** [comment]
Also, the app build is broken.

**Comment by toddmedema** [comment]
Ah yep, we're moving over to a new repo that combines all of our code to make it easier to share and consolidate code - https://github.com/ExpeditionRPG/expedition - can you make your changes on that repo? (The app is now in /services/repo; follow the setup instructions in the root README to get everything running)

**Comment by toddmedema** [comment]
Ah, probably a Windows thing... Scott and I dev on Unix-based OS's...

Thankfully, @smartin015 made a docker container setup for just this sort of thing! Could you share with ezittel how to get that set up? (the monorepo might need a bit of tweaking to work with it, but it seems well worth it now that we only have one repo to set up inside of Docker!)

**Comment by ezittel** [comment]
okay i'm getting my ubuntu disto up to shape then to make collaborating easier.

**Comment by ezittel** [comment]
I've moved over to my ubuntu machine for now, then.  Should be easier for now.  So my yarn tests is failing with a number of errors like this (this is the end of the run).  Any ideas?


 FAIL  app/Mail.test.ts
  ● Test suite failed to run

    ../../node_modules/@types/react/index.d.ts (2321,13): Subsequent variable declarations must have the same type.  Variable 'ol' must be of type 'DetailedHTMLProps<OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>', but here has type 'DetailedHTMLProps<OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>'.
      
      
      at Object.runTsDiagnostics (node_modules/ts-jest/dist/utils.js:136:15)
      at process (node_modules/ts-jest/dist/preprocessor.js:25:17)
      at Object.process (node_modules/ts-jest/index.js:8:51)


Test Suites: 25 failed, 25 total
Tests:       0 total
Snapshots:   0 total
Time:        79.297s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ezittel** [comment]
Doesn't really matter - npm run dev still gets the app running.

**Comment by toddmedema** [comment]
Ah yep, the testing setup is still broken in the monorepo - but as long as the app runs you can start working on it! Hoping to have the testing all sorted out in the next few days

**Comment by toddmedema** [comment]
Yeah! I've actually come across the spinner once or twice in the app while looking for it - I think it's primarily a problem that we aren't switching to the Search Results card soon enough

**Comment by ezittel** [comment]
That explains what's going on, I'm still not sure how to force the card to change though.

**Comment by toddmedema** [comment]
Walking through what happens on the search card:
1. The search button calls `search` in its container: https://github.com/ExpeditionRPG/expedition/blob/master/services/app/app/components/views/SearchContainer.tsx#L39
2. Which calls the `search` action: https://github.com/ExpeditionRPG/expedition/blob/master/services/app/app/actions/Search.tsx#L17
3. Note how the search action waits to dispatch `toCard` until the results are in - we should achieve the expected result by moving that dispatch to line 26 / before we make the web request.
