### ISSUE TITLE
Use standardized QuestListElement in saved quests + featured quests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-app#719]
*Migrated to expeditionrpg/expedition#258 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Aka we'll want to split this (and its tests) into its own components so that we can use it in multiple places - https://github.com/ExpeditionRPG/expedition-app/blob/master/app/components/views/Search.tsx#L305

**Comment by toddmedema** [comment]
Note that this should wait until https://github.com/ExpeditionRPG/expedition-app/pull/717 lands

**Comment by toddmedema** [comment]
@ezittel this would be another good practice PR after the paper and pen update :)
