### ISSUE TITLE
requirespenpaper field

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#720]
QDL, DB, API, QC, App search filters and show in "requires" list on quest details

**Comment by ezittel** [comment]
does it make some sense for me to grab this one, Todd?

**Comment by ezittel** [comment]
especially beause I have a quest that would benefit from this field :)

**Comment by toddmedema** [comment]
Good idea! You'll need to start by adding it as a field in the quest schema in QDL - https://github.com/ExpeditionRPG/expedition-qdl/blob/master/lib/schema/Quests.tsx

**Comment by ezittel** [comment]
For the API I have a question about how to do the declaration at line 30. Please review.
https://github.com/ExpeditionRPG/expedition-api/pull/121

**Comment by ezittel** [comment]
I need a hint about what to do with the DB and QC changes that you referenced from the original issue:

> QDL, DB, API, QC, App search filters and show in "requires" list on quest details

**Comment by ezittel** [comment]
and this - I did this differently but can put it under requires if you want
![image](https://user-images.githubusercontent.com/16277302/41071801-27883234-69c8-11e8-9e23-70f279e4de40.png)

**Comment by toddmedema** [comment]
Search seems fine for now, though I feel like there must be a more elegant way to do a yes / no / no preference selection...

As far as the details page, was thinking that `Expansions required` could be simplified to `Requires`, which could then take a list of requirements (for now just "Pen and Paper" and The Horror), and `.join(', ')` (or none if there are no requirements) - want to try that and take a screenshoot of a quest that requires nothing and a quest that requires both pen and paper and The Horror?

**Comment by ezittel** [comment]
It looks fine though the code seems rudimentary (I also lose the icons and wanted to use the book for penpaper) - is there a cleaner way?

![image](https://user-images.githubusercontent.com/16277302/41138694-02fb55c4-6ab1-11e8-884a-ec9cd24a89a8.png)
![image](https://user-images.githubusercontent.com/16277302/41138702-0f212144-6ab1-11e8-9d50-edabe570f913.png)

**Comment by ezittel** [comment]
Here is the QC PR 
https://github.com/ExpeditionRPG/expedition-quest-creator/pull/492

**Comment by toddmedema** [comment]
It's updated on the web app and gave you a shout out in the release notes, thank you so much for your help! https://www.reddit.com/r/expeditionrpg/comments/8qo655/app_improvements_1162/

If you're looking for another challenge and learning opportunity, this one seems like it would be a good fit: https://github.com/ExpeditionRPG/expedition-app/issues/718
